bases:
- environments.yaml
---
repositories:
- name: library-charts
  url: https://library-charts.k8s-at-home.com
- name: common
  url: https://bjw-s.github.io/helm-charts


helmfiles:
  - path: apps/common/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
  - path: apps/unifi-client/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
  - path: apps/unifi-ipmanager/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
      