bases:
- environments.yaml
---
repositories:
- name: common
  url: https://bjw-s.github.io/helm-charts


helmfiles:
  - path: apps/common/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
  - path: apps/unifi-client/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
  - path: apps/unifi-ipmanager/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
  - path: apps/ha-frontend/helmfile.yaml
    values:
    - environments/{{ .Environment.Name }}/values.yaml
    - environments/{{ .Environment.Name }}/images.yaml
      