releases:
  - name: home-automation-common-config
    chart: ./charts/{{`{{ .Release.Name }}`}}
    missingFileHandler: Warn
    values:
    - config/values.yaml.gotmpl
    - config/{{`{{ .Environment.Name }}`}}.yaml